project:
  type: website

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project Experience
      - href: Certificate.qmd
        text: Certificate
      - href: volunteer.qmd
        text: volunteer Experience
      - href: resume.qmd
        text: My Resume
        
  page-footer:
    center: |
      <small>
      Icons:
      <a href="https://www.flaticon.com/free-icons/travel" title="travel icons">Travel</a>,
      <a href="https://www.flaticon.com/free-icons/reading" title="reading icons">Reading</a>,
      <a href="https://www.flaticon.com/free-icons/analysis" title="analysis icons">Analysis</a>
      (Flaticon).
      </small>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
